# Generated by Django 5.0.6 on 2026-09-13 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("token_bucket", "Token Bucket"),
                            ("fixed_window", "Fixed Window"),
                            ("sliding_window", "Sliding Window Log"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("refill_rate", models.FloatField(blank=True, null=True)),
                ("limit", models.PositiveIntegerField(blank=True, null=True)),
                ("window_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("key_prefix", models.CharField(db_index=True, max_length=12)),
                ("owner", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("rate_limit_override", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="api_keys",
                        to="authentication.tier",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["key_hash"], name="authenticat_key_has_886d1f_idx"
                    )
                ],
            },
        ),
    ]
